### ISSUE TITLE
Cookbook Adoption List

### ISSUE THREAD

**Issue by damacus** [sous-chefs/meta#132]
# Possible Cookbooks 

- [ ] hostname: [See issue here](https://github.com/3ofcoins/chef-cookbook-hostname/issues/69)
- [ ] influxdb: [See issue here](https://github.com/bdangit/chef-influxdb/issues/180)
- [ ] prometheus: [See issue here](https://github.com/elijah/chef-prometheus/issues/100) note: we have an unforked fork of prometheus, but the source would be better

# Transfers Complete
